const actionTypes = {
    SET_LIST_VIEW: 'SET_LIST_VIEW',
    SET_RECIPES: 'SET_RECIPES',
    ADD_FAVORITE_RECIPE: 'ADD_FAVORITE_RECIPE',
    REMOVE_FAVORITE_RECIPE: 'REMOVE_FAVORITE_RECIPE',
    SET_FAVORITE_RECIPE: 'SET_FAVORITE_RECIPE',
}

export default actionTypes;